# Generated by Django 6.0.5 on 2026-05-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва тарифу')),
                ('plan_type', models.CharField(choices=[('INDIVIDUAL', 'Індивідуальні'), ('GROUP', 'Групові')], max_length=20, verbose_name='Тип занять')),
                ('lessons_count', models.PositiveIntegerField(verbose_name='Кількість занять')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='apps.subject', verbose_name='Предмет')),
            ],
        ),
    ]
