# Generated by Django 6.0.5 on 2026-05-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_left', models.PositiveIntegerField(verbose_name='Залишок занять')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.subscriptionplan', verbose_name='Тарифний план')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='apps.student', verbose_name='Студент')),
            ],
        ),
    ]
